catppuccin_frappe = {
        'bg' : "#51576d",
        'fg' : "#b5bfe2",
        'blue' : "#8caaee",
        'lavender' : "#babbf1",
        'sapphire' : "#85c1dc",
        'sky' : "#99d1db",
        'teal' : "#81c8be",
        'green' : "#a6d189",
        'yellow' : "#e5c890",
        'peach' : "#ef9f76",
        'maroon' : "#ea999c",
        'red' : "#e78284",
        'mauve' : "#ca9ee6",
        'pink' : "#f4b8e4",
        'flamingo' : "#eebebe",
        'rosewater' : "#f2d5cf",
        }
